---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-file-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: scw-bssd
  volumeMode: Filesystem
---
apiVersion: v1
kind: Pod
metadata:
  name: demo
  annotations:
    backup.velero.io/backup-volumes: "data"
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-webserver
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: my-file-pvc
